- name: "Windows Join Domain"
  hosts: all
  gather_facts: no
  become: true
  become_method: runas
  become_user: "administrator"
  tasks:
    - name: change hostname
      ansible.windows.win_hostname:
        name: "{{ instancename }}"
      register: res
    
    - name: reboot 1
      ansible.windows.win_reboot:
      when: res.reboot_required

    - name: "Join Domain"
      win_domain_membership:
        dns_domain_name: "{{ domain_name }}"
        domain_admin_user: "{{ domain_join_user }}@{{ domain_name }}"
        domain_admin_password: "{{ domain_user_pass }}"
        domain_ou_path: "{{ distinguishedname }}" # problem with DN "OU=Dev,OU=CRB Servers,DC=crb,DC=local"
        state: domain
      register: domain_state

    - win_reboot:
      when: domain_state.reboot_required